test:

#question 1
		
	# g++ -c question1.cpp
	# g++ -g -o debug1 question1.o
	# g++ -O3 -o optimized1 question1.o

#question 2
	g++ -c question2.cpp
	g++ -g -o debug1 question2.o
	g++ -O3 -o optimized1 question2.o